In [11]:
import pandas as pd 
worldcup2018=pd.read_csv(r"C:\Projects\worldcup-social-media-nlp\Data\FIFA.csv",delimiter=',')
worldcup2022=pd.read_csv(r"C:\Projects\worldcup-social-media-nlp\Data\fifa_world_cup_2022_tweets.csv", delimiter=',')

# worldcup2018 dataset

In [12]:
worldcup2018.columns

Index(['ID', 'lang', 'Date', 'Source', 'len', 'Orig_Tweet', 'Tweet', 'Likes',
       'RTs', 'Hashtags', 'UserMentionNames', 'UserMentionID', 'Name', 'Place',
       'Followers', 'Friends'],
      dtype='str')

In [13]:
common_ids = set(worldcup2018['ID']).intersection(set(worldcup2022['Unnamed: 0']))
print(len(common_ids))

0

**Remove unecessary columns**

In [14]:
worldcup2018=worldcup2018.drop(columns=['Followers','Friends','lang','len','ID','UserMentionNames', 'UserMentionID','Name','Orig_Tweet'])

In [15]:
worldcup2018.columns

Index(['Date', 'Source', 'Tweet', 'Likes', 'RTs', 'Hashtags', 'Place'], dtype='str')

In [16]:
worldcup2018.shape

(530000, 7)

In [17]:
worldcup2018.dtypes

Date          str
Source        str
Tweet         str
Likes       int64
RTs         int64
Hashtags      str
Place         str
dtype: object

**Correct Data Types**

In [18]:
#change the type of the column Date from str to datetime type
worldcup2018['Date']=pd.to_datetime(worldcup2018['Date'])
worldcup2018.dtypes

Date        datetime64[us]
Source                 str
Tweet                  str
Likes                int64
RTs                  int64
Hashtags               str
Place                  str
dtype: object

**Fix Empty Strings**

In [19]:
# Replace spaces, or only question marks ,NaNs with empty strings,
import numpy as np
str_cols=worldcup2018.select_dtypes(include=str).columns
worldcup2018[str_cols] = worldcup2018[str_cols].replace(r'^\s*$|^\?+$', np.nan, regex=True)
# fill missing text for NLP
worldcup2018[str_cols] = worldcup2018[str_cols].fillna('')

In [20]:
worldcup2018.head(5)

,Date,Source,Tweet,Likes,RTs,Hashtags,Place
0,2018-07-02 01:35:45,Twitter for Android,Only two goalkeepers have saved three penaltie...,0,477,"WorldCup,POR,ENG",Accra
1,2018-07-02 01:35:44,Twitter for Android,scores the winning penalty to send into the qu...,0,1031,WorldCup,Bogor
2,2018-07-02 01:35:42,Twitter for Android,Tonight we have big game,0,488,worldcup,
3,2018-07-02 01:35:41,Twitter Web Client,We get stronger Turn the music up now We got t...,0,0,"PowerByEXO,WorldCup,FIFAStadiumDJ,XiuminLeague","Zapopan, Jalisco"
4,2018-07-02 01:35:40,Twitter for Android,Only two goalkeepers have saved three penaltie...,0,477,"WorldCup,POR,ENG",

In [21]:
empty_tweets = worldcup2018['Tweet'].isnull()
empty_tweets_count = worldcup2018['Tweet'].isnull().sum()
empty_hashtags_count = worldcup2018.loc[empty_tweets, 'Hashtags'].isnull().sum()
print("Number of empty Tweets is :", empty_tweets_count)
print("Number of empty hashtags when Tweet is empty:", empty_hashtags_count)

Number of empty Tweets is : 0
Number of empty hashtags when Tweet is empty: 0

**Standardize text columns**

In [22]:
str_cols=worldcup2018.select_dtypes(include=str).columns
for col in str_cols:
    worldcup2018[col]= worldcup2018[col].str.strip().str.lower()

**Handle duplicants**

In [23]:
#chech duplicants
worldcup2018.duplicated().sum()

np.int64(4215)

In [24]:
# Show all duplicated rows
worldcup2018[worldcup2018.duplicated()]

,Date,Source,Tweet,Likes,RTs,Hashtags,Place
1468,2018-07-02 01:22:47,twitter for android,power by exo,0,1,"powerbyexo,worldcup,fifastadiumdj,xiuminleague",
1575,2018-07-02 01:21:54,twitter for iphone,gg gn and gl,0,4370,worldcup,
1983,2018-07-02 01:18:18,twitter for iphone,gg gn and gl,0,4370,worldcup,
2275,2018-07-02 01:15:31,twitter for iphone,japan have never made it past the last eight s...,0,221,,
2996,2018-07-02 01:09:14,twitter for android,power by exo,0,2,"powerbyexo,worldcup,fifastadiumdj,xiuminleague",
...,...,...,...,...,...,...,...
529531,2018-07-15 22:49:58,twitter for android,dear france congratulations on winning the of ...,0,96731,worldcup,
529588,2018-07-15 22:49:52,twitter for iphone,dear france congratulations on winning the of ...,0,96731,worldcup,
529627,2018-07-15 22:49:48,twitter for iphone,dear france congratulations on winning the of ...,0,96736,worldcup,
529860,2018-07-15 22:49:25,twitter for android,france just won the of its teams players are i...,0,19569,worldcup,
529912,2018-07-15 22:49:20,twitter for iphone,dear france congratulations on winning the of ...,0,96746,worldcup,

In [25]:
#Remove duplicated rows
worldcup2018 = worldcup2018.drop_duplicates()

In [26]:
worldcup2018.duplicated().sum()

np.int64(0)

In [27]:
worldcup2018["Tweet"].duplicated().sum()

np.int64(412712)

In [28]:
worldcup2018 = worldcup2018.drop_duplicates(subset=["Tweet"])
worldcup2018["Tweet"].duplicated().sum()

np.int64(0)

In [29]:
worldcup2018["Tweet"].nunique()

113073

In [30]:
worldcup2018.head(5)

,Date,Source,Tweet,Likes,RTs,Hashtags,Place
0,2018-07-02 01:35:45,twitter for android,only two goalkeepers have saved three penaltie...,0,477,"worldcup,por,eng",accra
1,2018-07-02 01:35:44,twitter for android,scores the winning penalty to send into the qu...,0,1031,worldcup,bogor
2,2018-07-02 01:35:42,twitter for android,tonight we have big game,0,488,worldcup,
3,2018-07-02 01:35:41,twitter web client,we get stronger turn the music up now we got t...,0,0,"powerbyexo,worldcup,fifastadiumdj,xiuminleague","zapopan, jalisco"
5,2018-07-02 01:35:40,twitter for android,we re looking strong going into the knockout s...,0,153,bramex,

**Save a clean copy**

In [31]:
worldcup2018.to_csv(r"C:\Projects\worldcup-social-media-nlp\Data\worldcup2018_clean.csv", index=False)

# worldcup2022 dataset

In [32]:
worldcup2022.columns

Index(['Unnamed: 0', 'Date Created', 'Number of Likes', 'Source of Tweet',
       'Tweet', 'Sentiment'],
      dtype='str')

**Delete unecessary Columns**

In [33]:
worldcup2022=worldcup2022.drop(columns='Unnamed: 0')

In [34]:
#check for duplicants
worldcup2022.duplicated().sum()

np.int64(0)

In [35]:
worldcup2022["Tweet"].duplicated().sum()

np.int64(164)

In [36]:
worldcup2018 = worldcup2018.drop_duplicates(subset=["Tweet"])
worldcup2018["Tweet"].duplicated().sum()

np.int64(0)

In [37]:
worldcup2018["Tweet"].nunique()

113073

In [38]:
#check for missing values
worldcup2022.isnull().sum()

Date Created       0
Number of Likes    0
Source of Tweet    0
Tweet              0
Sentiment          0
dtype: int64

**Correct Data Types**

In [39]:
worldcup2022['Date Created']=pd.to_datetime(worldcup2022['Date Created'])
worldcup2022.dtypes

Date Created       datetime64[us, UTC]
Number of Likes                  int64
Source of Tweet                    str
Tweet                              str
Sentiment                          str
dtype: object

**Standardize text columns**

In [40]:
str_colm=worldcup2022.select_dtypes(include='str')
for col in str_colm:
    worldcup2022[col]=worldcup2022[col].str.strip().str.lower()

**Save a clean copy**

In [41]:
worldcup2022.to_csv(r"C:\Projects\worldcup-social-media-nlp\Data\worldcup2022_clean.csv")